@baseUrl = http://localhost:4000

###

# @name view_home
GET {{baseUrl}}
Content-Type: application/json

###

# @name view_snippet
GET {{baseUrl}}/snippet/view?id=1
Content-Type: application/json

###

# @name create_snippet
POST {{baseUrl}}/snippet/create
Content-Type: application/json

{
  "title": "Snippet Title",
  "content": "Snippet Content"
}

###

# @name view_create_snippet
GET {{baseUrl}}/snippet/create
Content-Type: application/json